name: Upload artifact

on: [push, pull_request]

jobs:
  upload-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user -r tools/requirements.txt
      - name: generate doc
        run: |
          cd tools &&
          ./generate_document.py &&
          ./generate_zip.py
      - name: Upload zip
        uses: actions/upload-artifact@v2
        with:
          name: ac-library
          path: tools/ac-library.zip