name: Document

on:
  push:
    branches:
      - master
      - production
    tags:
      - 'v*'

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set branch name
        id: branch
        run: echo "::set-output name=BRANCH_NAME::${GITHUB_REF##*/}"
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --user -r tools/requirements.txt
      - name: Generate documents (and remove markdown)
        run: |
          cd tools &&
          ./generate_document.py &&
          rm ../document_ja/*.md ../document_en/*.md &&
          mkdir generated &&
          mv ../document_ja generated/ &&
          mv ../document_en generated/
      - name: Publish to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./tools/generated
          destination_dir: ${{ steps.branch.outputs.BRANCH_NAME }}
